### PR TITLE
Add monkey-patch to support Fullscreen delegation

### LINKED ISSUE #10: Fullscreen and other APIs
The specification talks about fullscreen, but it seems only payments is supported? Why is that?

### PR DESCRIPTION
**Pull request by mustaqahmed**
Closes #10

### CODE REVIEW

**Comment by mustaqahmed** [comment]
@annevk PTAL

**Comment by annevk** [comment]
It would help me if #9 got explored more and also https://github.com/w3ctag/design-reviews/issues/655#issuecomment-953690813. I don't really see why we are doing this one API at a time and not set something up that scales better.

**Comment by domenic** [comment]
I find @annevk's point compelling here, but from what I can tell this is the second delegated capability. IMO it's a fine working mode to start doing two things the longwinded/involved way, and then once those are established, do an editorial refactoring to make the call sites cleaner by abstracting away the logic.

I think that editorial refactoring should be a relatively high priority after landing this PR, though.

**Comment by mustaqahmed** [comment]
I would love to take a stab at #9 but that needs a bit of playing with more example capabilities.  More importantly, I will need some 1:1s with two of you to sense some of the insights, currently I am struggling to start that work!

@annevk: Would it be okay with you if I merge this and then focus on the editorial refactoring as @domenic suggested?

**Comment by annevk** [comment]
That is okay with me, but do we have agreement on what I stated in my W3C TAG review comment? At least some people there seemed to have a very different idea about this and I'd like to be sure we have agreement on the bigger picture.

**Comment by mustaqahmed** [comment]
Let's plan for a meeting to discuss both the TAG comment and the refactoring idea.  I will send out an email today.

**Pull request merged**
